### ISSUE TITLE
Can't save with any Graphicsv0.3.2 settings

### ISSUE THREAD

**Issue by BTR-kugutsu** [ore-/Graphics#122]
Hi Ore-sama
any settings cannot be saved with the scene. (cubemap, any lighting and post-processing settings)
ofc, instaled ExtensibleSaveFormat plugin.

installed:
Graphics v0.3.2
HS2API_1.12
BepInEx_x64_5.0.1.0
BepInEX Plugin r15.0

Are these features not yet implemented?
Or is it a bug?

thanks

**Comment by ore-** [comment]
@BTR-kugutsu sama, mine are saving perfectly fine. any errors in output_log.txt?

**Comment by ore-** [comment]
@BTR-kugutsu I assume you don't have problems saving. You can also try v0.3.3. Feel free to reopen if problem persists but if it does, please provide more specific info.
