### ISSUE TITLE
2 problems, presets not being detected and not working after Marco updated plugins

### ISSUE THREAD

**Issue by Chernobog95** [ore-/Graphics#124]
I have been playing around with HS2 iteration of Graphics plugins, made 2 or 3 dozen saves, compared stuff and what not. Since I can't delete presets in game. I have to quit the game. I deleted presets in the folder that I did not need. I return to the game and it doesn't show any preset despite being in folder.

...and...

After Marco released newer Bepis plugin, fixes and so on... After I applied it I pressed F5 in character maker. It doesn't show up. Something in those updates is cockblocking the graphics code.

**Comment by ore-** [comment]
Neither of these are issues with Graphics. Presets are clearly working before you did the removal. API updates clearly broke API contract and is a breaking change on the API side. Since preset removal can be done on the actual files, it's not a high priority to add delete within the menu.
