### ISSUE TITLE
Presets not being applied when between game modes

### ISSUE THREAD

**Issue by Chernobog95** [ore-/Graphics#127]
If one applies a preset in character maker, exists character maker to title menu, the preset is not applied, if preset applied to title menu, it won't be applied to hero's room, when applied to hero's room and going anywhere the preset won't be applied.

A work around is to have identical copy of the preset, have to every time activate menu and manually select the preset I want to use.

A less stressful workaround would be for a dedicated button that would apply last preset that was used.

A permanent solution would be to automatically do such.

**Comment by ore-** [comment]
it wouldn't make sense to do so. lighting conditions could vary greatly between scenes, i.e. maker, in game and in between game scenes, and preset is not designed to save lights.
