### ISSUE TITLE
Suggestion - Depth of Field, add a function to show in and out of focus plane

### ISSUE THREAD

**Issue by MonkeyDocs** [ore-/Graphics#74]
## Expected Behavior
An addition of in and out-of-focus plane for easier and more accurate DoF adjustment.

## Used AI_Graphics Version
v0.2.0

## Steps to Reproduce
1. A button to enable/disable to display DoF plane.

**Comment by ore-** [comment]
probably not going to do more than the advanced info exposed by https://github.com/ore-/Graphics/issues/125. now that autofocus works, you probably don't need this plane that effectively is debug info as you can just see the focal distance calculated by autofocus.
