### ISSUE TITLE
Add PCSS soft shadow

### ISSUE THREAD

**Issue by ore-** [ore-/Graphics#78]
https://github.com/TheMasonX/UnityPCSS or 
https://assetstore.unity.com/packages/vfx/shaders/next-gen-soft-shadows-137380

**Comment by hooh-hooah** [comment]
@ore- Added a code that adds PCSS shadow component when directional light is created in studio.
I failed to make it work but you still can try to see what's wrong.

Some error said cascaded shadow is disabled in the game but I can't sure about it..

**Comment by ore-** [comment]
@hooh-hooah sure will check, thx for testing

**Comment by ore-** [comment]
the https://github.com/TheMasonX/UnityPCSS solution turns out to be sub optimal. while shadow softness/falloff at a distance is nice, shadow close up in deferred without msaa looks terrible. I think this has to be abandoned. and ngss while nice it isn't free. will try segi first per #120
